apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- resources/deployment.yaml
images:
- name: ghcr.io/remcowesterhoud/techtalk-gitops
- name: ghcr.io/remcowesterhoud/techtalk-gitops:ghcr.io/remcowesterhoud/techtalk-gitops
  newTag: sha-0ccc977
