apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- resources/deployment.yaml
- resources/sealedsecrets.yaml
images:
- name: ghcr.io/remcowesterhoud/techtalk-gitops
  newTag: sha-63f55a6
