apiVersion: apps/v1
kind: Deployment
metadata:
  name: techtalk
  labels:
    app: techtalk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techtalk
  template:
    metadata:
      labels:
        app: techtalk
    spec:
      containers:
        - name: techtalk-gitops
          image: ghcr.io/remcowesterhoud/techtalk-gitops
          ports:
            - containerPort: 80
          env:
            - name: CLUSTER_ID
              valueFrom:
                secretKeyRef:
                  name: zeebe-secrets
                  key: CLUSTER_ID
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: zeebe-secrets
                  key: CLIENT_ID
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: zeebe-secrets
                  key: CLIENT_SECRET
            - name: REGION
              valueFrom:
                secretKeyRef:
                  name: zeebe-secrets
                  key: REGION
            - name: BASE_URL
              valueFrom:
                secretKeyRef:
                  name: zeebe-secrets
                  key: BASE_URL
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: zeebe-secrets
                  key: PORT
            - name: AUTH_URL
              valueFrom:
                secretKeyRef:
                  name: zeebe-secrets
                  key: AUTH_URL
